# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Simple Pipe

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      myVersion:
        description: 'Input Version'
      myValues:
        description: 'Input Values'
 
permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
     
    # Map a step output to a job output
    outputs:
      artifact-path: ${{ steps.setoutput.outputs.jarpath }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
        
    - name: Set timestamp
      run: echo TDS=$(date +'%Y-%m-%dT%H-%M-%S') >> $GITHUB_ENV 
      
    - name: Tag artifact
      run: mv build/libs/greetings-add.jar build/libs/greetings-add-${{github.event.inputs.myVersion }}${{ env.TDS }}.jar

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: greetings-jar
        path: |
          build/libs
          test-script.sh
        
    - name: Set output
      id: setoutput
      run: echo jarpath=build/libs/greetings-add-${{ github.event.inputs.myVersion}}${{ env.TDS }}.jar >> $GITHUB_OUTPUT
      
  print-build-output:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo ${{needs.build.outputs.artifact-path}}
      
  test-run:

     runs-on: ubuntu-latest
     needs: build
    
     steps:
     - name: Download candidate artifacts
       uses: actions/download-artifact@v3       
       with:
         name: greetings-jar
        
     - name: Execute test
       shell: bash
       env:
         ARGS: ${{ github.event.inputs.myValues }}
       run: |
         chmod +x ./test-script.sh
         ./test-script.sh ${{ needs.build.outputs.artifact-path }} "$ARGS"
         
  count-args:

    runs-on: ubuntu-latest 

    steps:
    - id: report-count
      uses: xandercm128/arg-count-action@main
      with:
        arguments-to-count: ${{ github.event.inputs.myValues }}
    - run: echo
    - shell: bash
      run: |
        echo argument count is ${{ steps.report-count.outputs.arg-count }} 
        #exit 1   #for testing create failure on issue
        
  create-issue-on-failure:
  
    permissions:
      issues: write
    needs: [test-run, count-args]
    if: always() && failure()
    uses: ./.github/workflows/create-failure-issue.yml
    with:
      title: "Automated workflow failure issue for commit ${{ github.sha }}"
      body: "This issue was automatically created by the GitHub Action workflow ** ${{github.workflow }} **"        
